### ISSUE TITLE
Docker Compose Error on Ubuntu

### ISSUE THREAD

**Issue by johko** [dioptra-ai/katiml#1]
Hey, 
your tool looks great and I wanted to give it a try.
But when building with `docker compose up --build` I'm running into an error:
```
[+] Running 0/4
 ⠇ mongo-cache Pulling                                                     1.8s
 ⠇ redis Pulling                                                           1.8s
 ⠇ postgres Pulling                                                        1.8s
 ⠿ mongo Error                                                             1.8s
no matching manifest for linux/amd64 in the manifest list entries
```

I'm trying to build on Ubuntu 22.04 if that is of relevance. Any idea why that happens and how I can solve it?

**Comment by pharnoux** [comment]
Thanks for raising. Looking into a fix

**Comment by pharnoux** [comment]
Looks like a M1 vs Intel issue. I updated the docker compose yaml. LMK if that solved the problem
